server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**

logging:
  level:
    org.springframework:
      cloud.gateway: trace
# 以下配置指定了应用的名称、使用的协议（Dubbo）、注册中心的类型（Nacos）和地址
dubbo:
  # 设置应用的名称
  application:
    name: dubbo-springboot-demo-consumer
    qos-enabled: true
    qos-port: 22224
    qos-access-forbidden: false
  # 指定使用 Dubbo 协议，且端口设置为 -1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: 22223
  # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
